development:
  adapter: mysql
  username: root
  password:
  database: trainwiki_development

test:
  adapter: mysql
  username: root
  password:
  database: trainwiki_test

production:
  adapter: mysql
  username: trainwiki
  password: "jump50,biked"
  database: trainwiki_production
